{
 "title": "KRG Waiter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size: 100px\">Waiter</h1>"
   }
  },
  { "title": "Current State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{instance=\"waiter.ucsd.edu:9100\",mode!=\"idle\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory in Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{instance=\"waiter.ucsd.edu:9100\"} + \r\nnode_memory_MemTotal_bytes{instance=\"waiter.ucsd.edu:9100\"}\r\n- node_memory_MemFree_bytes{instance=\"waiter.ucsd.edu:9100\"}\r\n- node_memory_Buffers_bytes{instance=\"waiter.ucsd.edu:9100\"}\r\n- node_memory_SReclaimable_bytes{instance=\"waiter.ucsd.edu:9100\"}\r\n- node_memory_Cached_bytes{instance=\"waiter.ucsd.edu:9100\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (node_filesystem_size_bytes{instance=\"waiter.ucsd.edu:9100\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"waiter.ucsd.edu:9100\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current eno1np0 Network Activity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"eno1np0\"}[30s])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"eno1np0\"}[30s])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Average CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (node_hwmon_temp_celsius{instance=\"waiter.ucsd.edu:9100\", chip=\"pci0000:00_0000:00:18_3\", sensor!=\"temp1\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Current GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (DCGM_FI_DEV_GPU_UTIL{instance=\"waiter.ucsd.edu:9400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current GPU Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"waiter.ucsd.edu:9400\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"waiter.ucsd.edu:9400\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GPU Power Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=\"waiter.ucsd.edu:9400\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ansible Last Deploy Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads_last_deploy{instance=\"waiter.ucsd.edu:9000\",job=\"ansible_deploy_monitor\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ansible Deploy Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ads_subprocess_retval{instance=\"waiter.ucsd.edu:9000\",job=\"ansible_deploy_monitor\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Ansible Last Check Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ads_last_run{instance=\"waiter.ucsd.edu:9000\",job=\"ansible_deploy_monitor\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{instance=\"waiter.ucsd.edu:9100\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{instance=\"waiter.ucsd.edu:9100\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"waiter.ucsd.edu:9100\", chip=\"pci0000:00_0000:00:18_3\", sensor!=\"temp1\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Memory History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Allocated Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Shared"
    },
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "SUnreclaim"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Swap Cached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Page Tables"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_MemFree_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_Buffers_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SReclaimable_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_Cached_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SUnreclaim_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SwapCached_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_PageTables_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Application Memory"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{instance=\"waiter.ucsd.edu:9100\"} + node_memory_SUnreclaim_bytes{instance=\"waiter.ucsd.edu:9100\"} + node_memory_SwapCached_bytes{instance=\"waiter.ucsd.edu:9100\"} + node_memory_PageTables_bytes{instance=\"waiter.ucsd.edu:9100\"} + node_memory_MemTotal_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_MemFree_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_Buffers_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SReclaimable_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_Cached_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SUnreclaim_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_SwapCached_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_PageTables_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"waiter.ucsd.edu:9100\"} - node_memory_Shmem_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "SReclaimable"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  { "title": "GPU History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Current GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_GPU_UTIL{instance=\"waiter.ucsd.edu:9400\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Current GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"waiter.ucsd.edu:9400\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"waiter.ucsd.edu:9400\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"waiter.ucsd.edu:9100\"}",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "eno1np0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"eno1np0\"}[$__interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"eno1np0\"}[$__interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "lo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"lo\"}[30s])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"lo\"}[30s])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "br-125925f6d3bc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"br-125925f6d3bc\"}[$__interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"br-125925f6d3bc\"}[$__interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "docker0",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"docker0\"}[30s])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"waiter.ucsd.edu:9100\",device=\"docker0\"}[30s])",
     "legendFormat": "Rx"
    }
   ]
  },
  { "title": "Storage Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Disk Usage on /",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_filesystem_size_bytes{instance=\"waiter.ucsd.edu:9100\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"waiter.ucsd.edu:9100\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_read_bytes_total{instance=\"waiter.ucsd.edu:9100\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_written_bytes_total{instance=\"waiter.ucsd.edu:9100\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_reads_completed_total{instance=\"waiter.ucsd.edu:9100\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by(instance) (rate(node_disk_writes_completed_total{instance=\"waiter.ucsd.edu:9100\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "NVME Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"waiter.ucsd.edu:9100\", chip=~\"nvme_nvme0|nvme_nvme2|nvme_nvme3|nvme_nvme1\"}",
     "legendFormat": "{{chip}}"
    }
   ]
  }
 ]
}