# Disk layout for waiter (declarative, via disko) — GREENFIELD scratch redesign.
#
# GOTCHA — disko is DESTRUCTIVE and not idempotent like `parted`/`zpool create`.
# `disko --mode disko` (or nixos-anywhere) wipes and repartitions EVERY device
# listed below, every run. There is no "only create what's missing". Coming from
# imperative `parted` + `zpool create`, treat this file as "what the disks WILL
# be made to look like", run once at install, then never re-run destructively on
# a live machine (use `--mode mount` to just import+mount on later boots).
#
# GOTCHA — device paths are /dev/disk/by-id/* on purpose (matches
# boot.zfs.devNodes). Do NOT use /dev/nvme0n1 / /dev/sda: those names reshuffle
# across controller/slot/enumeration changes and ZFS would fail to import. Fill
# the REPLACE-* placeholders from `ls -l /dev/disk/by-id/` on the target:
#   nvme  ->  nvme-<model>_<serial>          (NOT the *_1 partition aliases)
#   hdd   ->  wwn-0x...  or  ata-<model>_<serial>
#
# ============================================================================
# WHY THIS LAYOUT (the greenfield scratch redesign) — see docs/scratch-greenfield.md
# ----------------------------------------------------------------------------
# The old design tiered /scratch with autotier (a FUSE daemon) over an NVMe pool,
# an HDD mirror, and NFS. autotier crashed under concurrent small-file training
# reads (per-access RocksDB writes) and is unmaintained — so it's gone. This
# layout replaces it with ZFS-native tiering, no FUSE:
#
#   * nvmepool (RAIDZ1, 4× NVMe `os` partitions) — UNCHANGED ROLE: redundant OS +
#     /tools + /local. Survives one NVMe failure.
#   * scratchpool (ONE pool) — the new /scratch home:
#       - DATA  = 2× HDD whole-disk, STRIPED (~29 TiB, double the old mirror).
#                 No redundancy: scratch is regenerable; a disk loss = regenerate.
#       - SPECIAL = 4× NVMe `special` partitions, striped — metadata-only vdev, so
#                 listings/`find` over 29 TiB stay NVMe-fast. Striped (not mirrored)
#                 per the approved proposal: matches the data vdev's no-redundancy
#                 (so `zpool create` needs no -f) and is the same regenerable bet.
#                 NB: losing the special vdev loses the pool — accepted (regenerable).
#       - CACHE = 4× NVMe `cache` partitions, striped — L2ARC. Hot reads are served
#                 from RAM (ARC) then NVMe (L2ARC); cold data falls off the cache on
#                 its own. Losing an L2ARC device is harmless (it's only a cache).
#
# So the NVMe is split per disk into: ESP | os(nvmepool) | special(scratchpool) |
# cache(scratchpool) | slack. Reads of the active working set are NVMe-fast via
# ARC/L2ARC; bytes live on the striped HDD; metadata is always on NVMe. When the
# 29 TiB fills (future), modules/scratch.nix's overflow job demotes the coldest
# files to fabricant NFS and leaves a symlink — automatic, recoverable, no FUSE.
# ----------------------------------------------------------------------------
#
# GOTCHA — mountpoint policy. Boot-relevant datasets (root/nix/persist/tools) use
# `options.mountpoint = "legacy"` so NixOS `fileSystems.*` (generated by disko) is
# the single authority for what mounts where and in what order. We deliberately do
# NOT use ZFS-managed mountpoints for these: mixing zfs auto-mount with NixOS
# fileSystems causes double-mount / ordering races, and the impermanence rollback
# needs root mounted under NixOS's control. The scratch dataset is the opposite
# case — disko emits NO fileSystems entry for it (no top-level `mountpoint`), so
# modules/scratch.nix (krg.scratch) owns where it mounts (a plain ZFS mount now,
# NOT a FUSE layer). `mountpoint = "legacy"` for the krg dataset (mounted there);
# the e4e dataset stays `mountpoint = "none"` (reserved scaffolding — no e4e users
# yet). `zfs set mountpoint=…` is non-destructive, so flipping none<->legacy on a
# live box is safe (no reformat).
{...}: let
  # GOTCHA — RAIDZ1 uses the SMALLEST member. All four NVMe `os` partitions are an
  # identical size on identical disks, so they come out equal.
  # An independent ESP on every disk is what makes GRUB mirroredBoots work: each
  # disk is self-contained and bootable, so the box survives losing any one NVMe.
  # 2G (not 1G) because GRUB copyKernels stores kernels+initrds (ZFS initrds are
  # chunky) on the vfat ESP, and configurationLimit generations must all fit.
  espSize = "2G";

  # NVMe partition budget per 4 TB Crucial T700 (~3.638 TiB usable). The remainder
  # after ESP+os+special+cache (~0.7 TiB) is left UNPARTITIONED as SSD
  # overprovisioning (sustained-write endurance on the L2ARC churn).
  osSize = "1400G"; # -> nvmepool raidz1 (usable ≈ 3 × 1400G ≈ 4.1 TiB): OS+/tools+/local
  specialSize = "128G"; # -> scratchpool special (striped 4× = 512 GiB metadata space)
  cacheSize = "1400G"; # -> scratchpool L2ARC (striped 4× ≈ 5.5 TiB hot-read cache)

  # Topology members are referenced by the GPT partition label (set explicitly per
  # partition below). by-partlabel is what disko itself resolves disk-name shorthand
  # to under the hood, and it's necessary here because each NVMe is split across
  # TWO pools (nvmepool `os` + scratchpool `special`/`cache`), so the disk-name
  # shorthand (which assumes one zfs partition per disk) can't disambiguate.
  byPartlabel = l: "/dev/disk/by-partlabel/${l}";

  # Inherited-by-children pool root props. recordsize is intentionally left at the
  # ZFS default (128K) here and only overridden to 1M on the scratch dataset.
  zfsRootProps = {
    mountpoint = "none"; # pool root itself never mounts; children opt in
    compression = "zstd";
    atime = "off";
    xattr = "sa";
    acltype = "posixacl";
    "com.sun:auto-snapshot" = "false"; # default OFF; datasets opt in below
  };
in {
  disko.devices = {
    disk = {
      # ---- 4× NVMe: ESP + os(nvmepool) + special(scratchpool) + cache(scratchpool) ----
      nvme0 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B625F2"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = espSize;
              # type EF00 (EFI System) so UEFI firmware enumerates it as bootable.
              # Independent vfat ESP per disk — NOT a RAID member. GRUB installs to
              # all four via boot.loader.grub.mirroredBoots (hardware-configuration.nix)
              # and writes the EFI fallback path (\EFI\BOOT\BOOTX64.EFI) on each, so
              # firmware boots from whichever disk survives. Plain vfat (not the old
              # md "boot" array) because systemd-boot/GRUB install onto a real GPT
              # partition, never an md device.
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            os = {
              size = osSize;
              label = "nvme0-os";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
            special = {
              size = specialSize;
              label = "nvme0-special";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            cache = {
              size = cacheSize;
              label = "nvme0-cache";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
      nvme1 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B62604"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 2 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-1";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            os = {
              size = osSize;
              label = "nvme1-os";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
            special = {
              size = specialSize;
              label = "nvme1-special";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            cache = {
              size = cacheSize;
              label = "nvme1-cache";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
      nvme2 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B6261C"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 3 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-2";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            os = {
              size = osSize;
              label = "nvme2-os";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
            special = {
              size = specialSize;
              label = "nvme2-special";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            cache = {
              size = cacheSize;
              label = "nvme2-cache";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
      nvme3 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B6267C"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 4 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-3";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            os = {
              size = osSize;
              label = "nvme3-os";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
            special = {
              size = specialSize;
              label = "nvme3-special";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            cache = {
              size = cacheSize;
              label = "nvme3-cache";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };

      # ---- 2× HDD: whole-disk (single partition) -> scratchpool DATA (striped) ----
      hdd0 = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST16000NT001-3MC101_ZYDFDS0Q"; # Seagate 16TB
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              label = "hdd0";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
      hdd1 = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST16000NT001-3MC101_ZYDG9T5W"; # Seagate 16TB
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              label = "hdd1";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
    };

    # NOTE — no mdadm. The ESP is deliberately NOT raided: each disk carries its
    # own independent vfat ESP (above) and GRUB mirroredBoots installs to all four.
    # A software-RAID ESP is a dead end here — neither systemd-boot nor GRUB will
    # install onto an md device (they need a real GPT partition), and firmware can
    # only read a plain FAT partition, not an md array.

    zpool = {
      # ===================== nvmepool (RAIDZ1, no encryption) =================
      # The 4 `os` partitions form one raidz1 vdev (collected by content.pool).
      # OS + /tools + /local live here, redundant — survives one NVMe failure.
      nvmepool = {
        type = "zpool";
        mode = "raidz1";
        # -o (pool create) options:
        options = {
          ashift = "12"; # 4K sectors; wrong value is permanent for the vdev
          autotrim = "on"; # continuous TRIM on the NVMe pool (HDD pool omits this)
        };
        # -O (root dataset) options, inherited by all datasets:
        rootFsOptions = zfsRootProps;

        datasets = {
          root = {
            type = "zfs_fs";
            mountpoint = "/";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # rolled back, never snapshotted
            # @blank is captured EMPTY here (disko runs this hook right after `zfs
            # create`, before nixos-install), and the impermanence module rolls back
            # to it in initrd on every boot. CAVEAT (learned the hard way on waiter,
            # systemd 258): an empty root has no /usr, and systemd 258's PID1 FREEZES
            # with "Refusing to run in unsupported environment where /usr/ is not
            # populated" before tmpfiles can create /usr/bin/env. modules/impermanence.nix
            # therefore reseeds /usr/bin/env in the rolled-back root (initrd, after
            # sysroot.mount, before switch-root) so an empty @blank still boots. If that
            # service is ever removed, @blank must instead be snapshotted AFTER
            # nixos-install (so it already carries /usr/bin/env) — do NOT just leave it
            # empty. The `zfs list` guard keeps re-runs (e.g. --mode mount) from erroring.
            postCreateHook = ''
              zfs list -t snapshot -H -o name | grep -qx 'nvmepool/root@blank' \
                || zfs snapshot nvmepool/root@blank
            '';
          };

          nix = {
            type = "zfs_fs";
            mountpoint = "/nix";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # store is reproducible; don't waste snaps
          };

          persist = {
            type = "zfs_fs";
            mountpoint = "/persist";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "true"; # frequent+hourly+daily+weekly+monthly
          };

          tools = {
            type = "zfs_fs";
            mountpoint = "/tools";
            options.mountpoint = "legacy";
            # recordsize left at default 128K (mixed vendor binaries, not bulk data)
            options."com.sun:auto-snapshot" = "true";
          };

          # Docker state on its own dataset (not on root, not bind-mounted from
          # /persist). Two reasons: (1) image/layer churn would bloat /persist's
          # frequent+hourly snapshots; (2) it stays durable independent of the
          # impermanence rollback (when that's re-enabled, /var/lib/docker is a
          # real mount, NOT in the persist bind list). Snapshots OFF — images are
          # pullable and overlay2 layers aren't worth snapshotting.
          docker = {
            type = "zfs_fs";
            mountpoint = "/var/lib/docker";
            options.mountpoint = "legacy";
            # recordsize default 128K (overlay2 = many small files, not bulk data)
            options."com.sun:auto-snapshot" = "false";
          };

          # Node-local per-user fast cache (krg.localCache, modules/local-cache.nix):
          # /local/<user> holds regenerable, hot, NODE-local state that has no business
          # on the NFS /home — IDE remote servers (~/.vscode-server, ~/.cursor-server,
          # symlinked here) plus the cache class (XDG_CACHE_HOME, pip/HF/torch/conda-pkgs).
          # Pure NVMe (no FUSE, no NFS, no tiering) so file-watching/inotify and small-file
          # I/O are fast, and it's OFF the @blank rollback so caches survive reboots (no
          # re-download). NO top-level `mountpoint` -> disko emits no fileSystems entry;
          # modules/local-cache.nix owns the legacy /local mount.
          # autosnapshot OFF (it's cache); quota caps it (no reservation — evictable).
          local = {
            type = "zfs_fs";
            options = {
              mountpoint = "legacy"; # /local mount owned by krg.localCache
              # recordsize default 128K (vscode-server + caches = many small files)
              quota = "1T";
              "com.sun:auto-snapshot" = "false";
            };
          };
        };
      };

      # ===================== scratchpool (HDD data + NVMe special/cache) ======
      # The new /scratch home. ONE pool spanning the striped HDD (data), the striped
      # NVMe `special` partitions (metadata-only vdev), and the striped NVMe `cache`
      # partitions (L2ARC). The vdev ROLES are assigned by mode.topology — content.pool
      # only says "this partition belongs to scratchpool"; without the topology disko
      # would make every member a data vdev (wrong — the NVMe must be special/cache).
      #
      # GOTCHA — NO redundancy anywhere in this pool (data striped, special striped,
      # cache always non-redundant). A single HDD or `special`-NVMe failure loses the
      # whole pool. Accepted: scratch is REGENERABLE (see docs/scratch-greenfield.md),
      # this doubles capacity vs a mirror, and smartd (compute profile) warns early.
      scratchpool = {
        type = "zpool";
        mode = {
          topology = {
            type = "topology";
            # DATA: 2× HDD as two single-disk vdevs => STRIPED (~29 TiB). Where the
            # bytes live. Striped, not mirrored, to double capacity (regenerable).
            vdev = [
              { members = [ (byPartlabel "hdd0") ]; }
              { members = [ (byPartlabel "hdd1") ]; }
            ];
            # SPECIAL: metadata-only vdev, 4× NVMe striped. Keeps directory listings /
            # find fast over 29 TiB. Striped matches the data vdev's no-redundancy.
            special = [
              { members = [ (byPartlabel "nvme0-special") ]; }
              { members = [ (byPartlabel "nvme1-special") ]; }
              { members = [ (byPartlabel "nvme2-special") ]; }
              { members = [ (byPartlabel "nvme3-special") ]; }
            ];
            # CACHE (L2ARC): hot-read cache, 4× NVMe striped. Losing it is harmless.
            cache = [
              (byPartlabel "nvme0-cache")
              (byPartlabel "nvme1-cache")
              (byPartlabel "nvme2-cache")
              (byPartlabel "nvme3-cache")
            ];
          };
        };
        options.ashift = "12"; # 4K sectors (the HDDs report 4Kn); permanent
        rootFsOptions = zfsRootProps;

        datasets = {
          # The krg lab's scratch — mounted at /scratch/krg by modules/scratch.nix
          # (a PLAIN ZFS mount now; the autotier FUSE layer is gone). No top-level
          # `mountpoint` -> disko emits no fileSystems entry.
          scratch-krg = {
            type = "zfs_fs";
            options = {
              mountpoint = "legacy"; # /scratch/krg mount owned by krg.scratch
              recordsize = "1M"; # sharded bulk data (WebDataset/tar/MDS); large records
              # relatime so the overflow mover can sort by last-access (LRU) to pick the
              # coldest files to demote — atime=off (pool default) would hide that, and
              # mtime would wrongly treat an actively-READ-but-unmodified shard as cold.
              atime = "on";
              relatime = "on";
              # Snapshots OFF — DELIBERATE. (1) scratch is regenerable, and important
              # work belongs on /home (NFS); (2) snapshots would PIN blocks the overflow
              # mover frees when it demotes a file to NFS, defeating capacity relief. The
              # COLD copies on fabricant NFS ARE snapshotted (ansible nfs_server), so
              # archived data still has accidental-rm protection — just not the hot tier.
              "com.sun:auto-snapshot" = "false";
            };
          };
          # E4E lab scaffolding — no e4e users/box yet, so unmounted. e4e will later
          # get e4e-nas as its NFS-overflow target (separate work). Add a
          # `projects.e4e` to krg.scratch + flip this mountpoint=none -> legacy then.
          scratch-e4e = {
            type = "zfs_fs";
            options = {
              mountpoint = "none";
              recordsize = "1M";
              "com.sun:auto-snapshot" = "false";
            };
          };
        };
      };
    };
  };
}
