# Disk layout for waiter (declarative, via disko).
#
# GOTCHA — disko is DESTRUCTIVE and not idempotent like `parted`/`zpool create`.
# `disko --mode disko` (or nixos-anywhere) wipes and repartitions EVERY device
# listed below, every run. There is no "only create what's missing". Coming from
# imperative `parted` + `zpool create`, treat this file as "what the disks WILL
# be made to look like", run once at install, then never re-run destructively on
# a live machine (use `--mode mount` to just import+mount on later boots).
#
# GOTCHA — device paths are /dev/disk/by-id/* on purpose (matches
# boot.zfs.devNodes). Do NOT use /dev/nvme0n1 / /dev/sda: those names reshuffle
# across controller/slot/enumeration changes and ZFS would fail to import. Fill
# the REPLACE-* placeholders from `ls -l /dev/disk/by-id/` on the target:
#   nvme  ->  nvme-<model>_<serial>          (NOT the *_1 partition aliases)
#   hdd   ->  wwn-0x...  or  ata-<model>_<serial>
#
# Pools/datasets created here (see CLAUDE-style summary):
#   nvmepool  raidz1 (4x NVMe, 1 parity)  ashift=12 zstd atime=off xattr=sa posixacl
#     root    legacy /          rolled back to @blank every boot (autosnap OFF)
#     nix     legacy /nix       never rolled back (autosnap OFF, store is reproducible)
#     persist legacy /persist   durable OS state (autosnap ON, all cadences)
#     tools   legacy /tools     vendor binaries (autosnap ON, all cadences)
#     docker  legacy /var/lib/docker  container state (autosnap OFF; layer churn)
#     scratch-krg  UNMOUNTED    quota=8T  reservation=2T  recordsize=1M
#     scratch-e4e  UNMOUNTED    quota=8T  reservation=2T  recordsize=1M
#   hddpool   mirror (2x HDD)             ashift=12 zstd atime=off xattr=sa posixacl
#     scratch-krg  UNMOUNTED    quota=10T reservation=4T  recordsize=1M
#     scratch-e4e  UNMOUNTED    quota=10T reservation=4T  recordsize=1M
#
# GOTCHA — mountpoint policy. Boot-relevant datasets (root/nix/persist/tools) use
# `options.mountpoint = "legacy"` so NixOS `fileSystems.*` (generated by disko) is
# the single authority for what mounts where and in what order. We deliberately do
# NOT use ZFS-managed mountpoints for these: mixing zfs auto-mount with NixOS
# fileSystems causes double-mount / ordering races, and the impermanence rollback
# needs root mounted under NixOS's control. The scratch datasets are the opposite
# case — created with `mountpoint = "none"` (you chose "unmounted"); they hold all
# their quota/reservation/recordsize props but mount nowhere until autotier wires
# them. `zfs set mountpoint=...` later is non-destructive.
{...}: let
  # GOTCHA — RAIDZ1 uses the SMALLEST member. All four NVMe zfs partitions are
  # "100%" of an identical disk minus an identical 2G ESP, so they come out equal.
  # An independent ESP on every disk is what makes GRUB mirroredBoots work: each
  # disk is self-contained and bootable, so the box survives losing any one NVMe.
  # 2G (not 1G) because GRUB copyKernels stores kernels+initrds (ZFS initrds are
  # chunky) on the vfat ESP, and configurationLimit generations must all fit.
  espSize = "2G";

  # Inherited-by-children pool root props. recordsize is intentionally left at the
  # ZFS default (128K) here and only overridden to 1M on the scratch datasets.
  zfsRootProps = {
    mountpoint = "none"; # pool root itself never mounts; children opt in
    compression = "zstd";
    atime = "off";
    xattr = "sa";
    acltype = "posixacl";
    "com.sun:auto-snapshot" = "false"; # default OFF; datasets opt in below
  };
in {
  disko.devices = {
    disk = {
      # ---- 4x NVMe: tiny mirrored ESP + rest to nvmepool raidz1 ----
      nvme0 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B625F2"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = espSize;
              # type EF00 (EFI System) so UEFI firmware enumerates it as bootable.
              # Independent vfat ESP per disk — NOT a RAID member. GRUB installs to
              # all four via boot.loader.grub.mirroredBoots (hardware-configuration.nix)
              # and writes the EFI fallback path (\EFI\BOOT\BOOTX64.EFI) on each, so
              # firmware boots from whichever disk survives. Plain vfat (not the old
              # md "boot" array) because systemd-boot/GRUB install onto a real GPT
              # partition, never an md device.
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
          };
        };
      };
      nvme1 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B62604"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 2 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-1";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
          };
        };
      };
      nvme2 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B6261C"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 3 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-2";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
          };
        };
      };
      nvme3 = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-CT4000T700SSD3_2422E8B6267C"; # Crucial T700 4TB
        content = {
          type = "gpt";
          partitions = {
            # Mirror member 4 of the GRUB mirroredBoots set; see nvme0's ESP.
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot-3";
                mountOptions = [ "umask=0077" "nofail" ];
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "nvmepool";
              };
            };
          };
        };
      };

      # ---- 2x HDD: whole-disk (single partition) to hddpool mirror ----
      hdd0 = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST16000NT001-3MC101_ZYDFDS0Q"; # Seagate 16TB
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "hddpool";
              };
            };
          };
        };
      };
      hdd1 = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST16000NT001-3MC101_ZYDG9T5W"; # Seagate 16TB
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "hddpool";
              };
            };
          };
        };
      };
    };

    # NOTE — no mdadm. The ESP is deliberately NOT raided: each disk carries its
    # own independent vfat ESP (above) and GRUB mirroredBoots installs to all four.
    # A software-RAID ESP is a dead end here — neither systemd-boot nor GRUB will
    # install onto an md device (they need a real GPT partition), and firmware can
    # only read a plain FAT partition, not an md array.

    zpool = {
      # ===================== nvmepool (RAIDZ1, no encryption) =================
      nvmepool = {
        type = "zpool";
        mode = "raidz1"; # all 4 `pool = "nvmepool"` partitions form one raidz1 vdev
        # -o (pool create) options:
        options = {
          ashift = "12"; # 4K sectors; wrong value is permanent for the vdev
          autotrim = "on"; # continuous TRIM on the NVMe pool (HDD pool omits this)
        };
        # -O (root dataset) options, inherited by all datasets:
        rootFsOptions = zfsRootProps;

        datasets = {
          root = {
            type = "zfs_fs";
            mountpoint = "/";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # rolled back, never snapshotted
            # GOTCHA — @blank must capture an EMPTY root. disko runs this hook
            # immediately after `zfs create`, before nixos-install writes anything,
            # so the snapshot is of a pristine dataset. The impermanence module
            # rolls back to exactly this in initrd on every boot. The `zfs list`
            # guard keeps re-runs (e.g. --mode mount) from erroring.
            postCreateHook = ''
              zfs list -t snapshot -H -o name | grep -qx 'nvmepool/root@blank' \
                || zfs snapshot nvmepool/root@blank
            '';
          };

          nix = {
            type = "zfs_fs";
            mountpoint = "/nix";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # store is reproducible; don't waste snaps
          };

          persist = {
            type = "zfs_fs";
            mountpoint = "/persist";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "true"; # frequent+hourly+daily+weekly+monthly
          };

          tools = {
            type = "zfs_fs";
            mountpoint = "/tools";
            options.mountpoint = "legacy";
            # recordsize left at default 128K (mixed vendor binaries, not bulk data)
            options."com.sun:auto-snapshot" = "true";
          };

          # Docker state on its own dataset (not on root, not bind-mounted from
          # /persist). Two reasons: (1) image/layer churn would bloat /persist's
          # frequent+hourly snapshots; (2) it stays durable independent of the
          # impermanence rollback (when that's re-enabled, /var/lib/docker is a
          # real mount, NOT in the persist bind list). Snapshots OFF — images are
          # pullable and overlay2 layers aren't worth snapshotting.
          docker = {
            type = "zfs_fs";
            mountpoint = "/var/lib/docker";
            options.mountpoint = "legacy";
            # recordsize default 128K (overlay2 = many small files, not bulk data)
            options."com.sun:auto-snapshot" = "false";
          };

          scratch-krg = {
            type = "zfs_fs";
            # No top-level `mountpoint` -> disko emits no fileSystems entry.
            options = {
              mountpoint = "none"; # unmounted until autotier wires it
              recordsize = "1M";
              quota = "8T"; # cap (oversubscribed on purpose; see note below)
              reservation = "2T"; # the actual guaranteed floor
              "com.sun:auto-snapshot" = "true";
              "com.sun:auto-snapshot:frequent" = "false"; # scratch: skip 15-min churn
              "com.sun:auto-snapshot:hourly" = "false"; # daily/weekly/monthly only
            };
          };
          scratch-e4e = {
            type = "zfs_fs";
            options = {
              mountpoint = "none";
              recordsize = "1M";
              quota = "8T";
              reservation = "2T";
              "com.sun:auto-snapshot" = "true";
              "com.sun:auto-snapshot:frequent" = "false";
              "com.sun:auto-snapshot:hourly" = "false";
            };
          };
        };
      };

      # ===================== hddpool (mirror, no encryption) ==================
      # GOTCHA — capacity math. ~16 TiB usable mirror; quota 10T+10T = 20T
      # OVERSUBSCRIBES it. That's deliberate thin-provisioning: quotas are caps,
      # the 4T+4T reservations (8T) are what's actually guaranteed and fit. Same
      # story on nvmepool (8T+8T quota over ~10.5 TiB usable raidz1, shared with
      # root/nix/persist/tools; 2T+2T reserved). reservation, not refreservation,
      # so the guarantee covers each dataset's snapshots too.
      hddpool = {
        type = "zpool";
        mode = "mirror"; # both `pool = "hddpool"` partitions -> one mirror vdev
        options.ashift = "12"; # no autotrim: spinning disks
        rootFsOptions = zfsRootProps;

        datasets = {
          scratch-krg = {
            type = "zfs_fs";
            options = {
              mountpoint = "none";
              recordsize = "1M";
              quota = "10T";
              reservation = "4T";
              "com.sun:auto-snapshot" = "true";
              "com.sun:auto-snapshot:frequent" = "false";
              "com.sun:auto-snapshot:hourly" = "false";
            };
          };
          scratch-e4e = {
            type = "zfs_fs";
            options = {
              mountpoint = "none";
              recordsize = "1M";
              quota = "10T";
              reservation = "4T";
              "com.sun:auto-snapshot" = "true";
              "com.sun:auto-snapshot:frequent" = "false";
              "com.sun:auto-snapshot:hourly" = "false";
            };
          };
        };
      };
    };
  };
}
