# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Unix domain socket connections
local   all             all                                     trust
# IPv4 local connections
host    all             all             127.0.0.1/32            trust
# IPv6 local connections
host    all             all             ::1/128                 trust
# Replication
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

# Docker internal network (172.16.0.0/12 covers Docker default subnets)
host    all             postgres        172.0.0.0/10            scram-sha-256
host    label_studio    label_studio_pg 172.0.0.0/10            scram-sha-256
