# krg.scratch — tiered /scratch via autotier (FUSE), per independent lab.
#
# WHAT: each lab (project) gets ONE merged /scratch/<lab> mount that autotier
# (45Drives, a passthrough FUSE fs) backs with several tiers, fastest-first. New
# writes land on the fastest tier with room; a periodic pass demotes the least
# "popular" files down the tiers and promotes hot ones back up — so the working
# set stays on NVMe and cold data drains to cheaper/larger storage automatically.
#
# WHY autotier and not plain per-pool mounts: the user wanted ONE namespace per
# lab with automatic hot/cold placement (NVMe -> local HDD -> NFS), not a manual
# fast/bulk split. The trade-offs accepted: a FUSE layer (overhead + a daemon
# failure mode) and tier-spanning snapshot semantics. See the design notes below.
#
# WAITER TOPOLOGY (the only consumer today, krg lab only — e4e has no users yet):
#   /scratch/krg  (autotierfs)
#     Tier 1  nvmepool/scratch-krg   -> /srv/scratch-tiers/nvme/krg   (NVMe, hot)
#     Tier 2  hddpool/scratch-krg    -> /srv/scratch-tiers/hdd/krg    (HDD mirror)
#     Tier 3  fabricant NFS          -> /srv/scratch-tiers/nfs/krg    (cold, network)
#
# LAB ISOLATION (krg and e4e are INDEPENDENT labs sharing this box): each lab's
# /scratch and tier roots are chmod 2770, group = that lab's AD group (krg ->
# "Kastner Research Group"), so one lab cannot read another's data even on shared
# hardware. allow_other,default_permissions makes the kernel enforce those modes
# through the FUSE layer. The NFS tier is exported no_root_squash so autotier
# (root) preserves each file's owner/group when it demotes onto the cold tier.
#
# IMPERMANENCE: the two LOCAL tiers are their own ZFS datasets (off nvmepool/root),
# so they survive the boot rollback untouched. autotier's RocksDB metadata defaults
# to /var/lib/autotier (on the rolled-back root) — it is persisted in
# modules/impermanence.nix, and pointed per-lab at /var/lib/autotier/<lab> so two
# autotier instances never share one RocksDB. If the cold (NFS) tier is down the
# autotier unit FAILS CLOSED (RequiresMountsFor below) rather than demoting files
# onto the ephemeral root — the same hazard the modules/nfs-home.nix login gate
# guards. The local tiers stay durable regardless.
#
# GOTCHA — autotierfs daemonizes. It calls libfuse's fuse_main() and exposes no
# foreground flag, so it double-forks into the background -> the service is
# Type=forking (NOT simple/oneshot, which would mis-track or hang). Stop unmounts
# with fusermount3 (libfuse3: the fuse_operations use copy_file_range/lseek).
{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.krg.scratch;

  # Hardened NFS options for a cold tier — identical posture to modules/nfs-home.nix:
  # _netdev+nofail so a down server never blocks boot, hard so no silent loss once
  # mounted, nconnect for throughput, bounded mount-timeout so a hung server can't
  # stall. The autotier unit's RequiresMountsFor makes "tier down" fail closed.
  nfsTierOptions = [
    "nfsvers=4.2"
    "hard"
    "noatime"
    "nconnect=4"
    "_netdev"
    "nofail"
    "x-systemd.mount-timeout=30s"
  ];

  # Where a tier's backing storage is mounted: <tierMountBase>/<tier.id>/<lab>.
  tierPath = projName: tier: "${cfg.tierMountBase}/${tier.id}/${projName}";

  # Per-lab RocksDB metadata dir (must differ per instance, see header).
  metadataPath = projName: "${cfg.metadataBase}/${projName}";

  # --- one autotier config file per lab ---------------------------------------
  # autotier.conf: [Global] + one [<label>] section per tier (order = priority,
  # fastest first). Quota is the fullness high-water mark that triggers demotion
  # to the next tier; the last tier is the overflow (Quota = 100 %).
  mkConfig = projName: proj:
    pkgs.writeText "autotier-${projName}.conf" (''
      # Generated by krg.scratch (nix/modules/scratch.nix) — do not edit on-box.
      [Global]
      Log Level = ${toString proj.logLevel}
      Tier Period = ${toString proj.tierPeriod}
      Metadata Path = ${metadataPath projName}
      Copy Buffer Size = ${proj.copyBufferSize}
    ''
    + concatMapStrings (tier: ''

      [${tier.label}]
      Path = ${tierPath projName tier}
      Quota = ${tier.quota}
    '') proj.tiers);

  # --- ownership / isolation step (ExecStartPre) ------------------------------
  # Runs AFTER the tier mounts are active (RequiresMountsFor) and after sssd, so
  # the AD lab group resolves. Always chmod 2770 the tier roots; chgrp to the lab
  # group only if it resolves — TOLERANT so /scratch still comes up (root-owned,
  # admin-only) before the AD join / group creation lands, then tightens on the
  # next start. The group name has spaces ("Kastner Research Group"), so every
  # path is chgrp'd individually with the group quoted.
  mkPermsScript = projName: proj:
    pkgs.writeShellScript "krg-scratch-perms-${projName}" ''
      set -u
      roots="${concatMapStringsSep " " (tier: tierPath projName tier) proj.tiers}"
      for d in $roots; do
        ${pkgs.coreutils}/bin/chmod 2770 "$d" || \
          echo "krg.scratch[${projName}]: chmod 2770 $d failed" >&2
      done
      ${optionalString (proj.ownerGroup != null) ''
        if ${pkgs.getent}/bin/getent group ${escapeShellArg proj.ownerGroup} >/dev/null 2>&1; then
          for d in $roots; do
            ${pkgs.coreutils}/bin/chgrp ${escapeShellArg proj.ownerGroup} "$d" || \
              echo "krg.scratch[${projName}]: chgrp failed on $d" >&2
          done
        else
          echo "krg.scratch[${projName}]: group ${escapeShellArg proj.ownerGroup} not resolvable yet (AD join/group pending?) — tier roots left root-owned (admin-only), will apply on next start" >&2
        fi
      ''}
      exit 0
    '';

  tierType = types.submodule ({ ... }: {
    options = {
      id = mkOption {
        type = types.str;
        example = "nvme";
        description = "Short slug for the tier mount path (<tierMountBase>/<id>/<lab>). Must be unique within a lab.";
      };
      label = mkOption {
        type = types.str;
        example = "NVMe";
        description = "autotier section name (shown by `autotier status`, used by `autotier pin`). May contain spaces.";
      };
      fsType = mkOption {
        type = types.enum [ "zfs" "nfs" ];
        description = "How the tier's backing storage is mounted: a local legacy-mountpoint ZFS dataset, or an NFS export.";
      };
      device = mkOption {
        type = types.str;
        example = "nvmepool/scratch-krg";
        description = "fileSystems device: ZFS dataset name (fsType=zfs) or `server:/export` (fsType=nfs).";
      };
      quota = mkOption {
        type = types.str;
        default = "100 %";
        example = "85 %";
        description = "autotier tier fullness cap (`N %` or `N [prefix]B`). Demotion to the next tier keeps usage under this. Give the last (overflow) tier `100 %`.";
      };
      mountOptions = mkOption {
        type = types.listOf types.str;
        default = [ ];
        description = "Extra mount options appended to the per-fsType defaults.";
      };
    };
  });

  # `attrsOf (submodule …)` binds `name` to the attribute key (the lab name), so
  # mountPoint defaults to /scratch/<lab>. (config below reads the same key via
  # mapAttrsToList, which is why tier paths / metadata / unit names were already right.)
  projectType = types.submodule ({ name, ... }: {
    options = {
      mountPoint = mkOption {
        type = types.str;
        default = "/scratch/${name}";
        description = "The merged FUSE mountpoint users see.";
      };
      ownerGroup = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "Kastner Research Group";
        description = ''
          Lab group that owns this scratch tree (mode 2770, setgid) so other labs
          are denied. An AD/SSSD group (may contain spaces). null = leave root-owned
          (admin-only). When set, the unit orders after sssd so the group resolves.
        '';
      };
      tierPeriod = mkOption {
        type = types.ints.unsigned;
        default = 86400;
        description = "Seconds between autotier demotion/promotion passes. Daily by default — scratch doesn't need aggressive churn, and it keeps NFS-tier traffic down.";
      };
      copyBufferSize = mkOption {
        type = types.str;
        default = "16 MiB";
        description = "autotier inter-tier copy buffer (bulk 1M-recordsize data moves faster with a larger buffer).";
      };
      logLevel = mkOption {
        type = types.enum [ 0 1 2 ];
        default = 1;
        description = "autotier log level (0 none, 1 normal, 2 debug).";
      };
      tiers = mkOption {
        type = types.listOf tierType;
        description = "Tiers fastest-first. At least two required.";
      };
    };
  });
in {
  options.krg.scratch = {
    enable = mkEnableOption "tiered /scratch via autotier (per-lab, FUSE)";

    package = mkOption {
      type = types.package;
      default = pkgs.autotier;
      defaultText = literalExpression "pkgs.autotier";
      description = "The autotier package providing autotierfs.";
    };

    tierMountBase = mkOption {
      type = types.str;
      default = "/srv/scratch-tiers";
      description = "Parent dir under which each tier's backing storage is mounted (admin-facing; users use the merged mountPoint).";
    };

    metadataBase = mkOption {
      type = types.str;
      default = "/var/lib/autotier";
      description = ''
        Parent dir for autotier's per-lab RocksDB metadata (<metadataBase>/<lab>).
        On an impermanent host this must be persisted (see modules/impermanence.nix);
        losing it only costs popularity history (autotier rebuilds), not data.
      '';
    };

    fuseOptions = mkOption {
      type = types.listOf types.str;
      default = [ "allow_other" "default_permissions" ];
      description = ''
        FUSE mount options. default_permissions makes the kernel enforce the
        underlying 2770/file modes (the lab-isolation gate); allow_other lets users
        other than the mounting root (i.e. everyone, gated by those modes) access it.
        allow_other needs programs.fuse.userAllowOther (set below).
      '';
    };

    projects = mkOption {
      type = types.attrsOf projectType;
      default = { };
      description = "Per-lab tiered scratch instances, keyed by lab name.";
      example = literalExpression ''
        {
          krg = {
            ownerGroup = "Kastner Research Group";
            tiers = [
              { id = "nvme"; label = "NVMe"; fsType = "zfs"; device = "nvmepool/scratch-krg"; quota = "85 %"; }
              { id = "hdd";  label = "HDD";  fsType = "zfs"; device = "hddpool/scratch-krg";  quota = "90 %"; }
              { id = "nfs";  label = "NFS (fabricant)"; fsType = "nfs"; device = "137.110.161.98:/srv/nfs/scratch-krg"; quota = "100 %"; }
            ];
          };
        }
      '';
    };
  };

  config = mkIf (cfg.enable && cfg.projects != { }) (
    let
      projectList = mapAttrsToList (name: proj: { inherit name proj; }) cfg.projects;
    in {
      assertions = mapAttrsToList (name: proj: {
        assertion = length proj.tiers >= 2;
        message = "krg.scratch.projects.${name}: autotier needs at least two tiers.";
      }) cfg.projects;

      # allow_other requires user_allow_other in /etc/fuse.conf (even though
      # autotierfs runs as root, libfuse checks it).
      programs.fuse.userAllowOther = true;

      # Admins want `autotier status -c …`, `which-tier`, `pin`, etc. on PATH.
      environment.systemPackages = [ cfg.package ];

      # One backing mount per tier, per lab. Local ZFS tiers mirror disko's legacy
      # mounts (fsType=zfs, "defaults"); we add "nofail" so a scratch hiccup never
      # blocks boot (the autotier unit depends on the mounts via RequiresMountsFor,
      # so it just won't start). The NFS tier uses the hardened nfs-home posture.
      fileSystems = mkMerge (concatMap ({ name, proj }:
        map (tier: {
          ${tierPath name tier} =
            if tier.fsType == "zfs" then {
              device = tier.device;
              fsType = "zfs";
              options = [ "defaults" "nofail" ] ++ tier.mountOptions;
            } else {
              device = tier.device;
              fsType = "nfs";
              options = nfsTierOptions ++ tier.mountOptions;
            };
        }) proj.tiers
      ) projectList);

      # Ensure the merged FUSE mountpoints exist (no .mount unit creates them, unlike
      # the tier backings). 0755 here is just the bare mountpoint; once autotier is
      # mounted the root's perms come from tier 1 (2770, set by the perms step).
      systemd.tmpfiles.rules =
        [ "d /scratch 0755 root root -" ]
        ++ map ({ name, proj }: "d ${proj.mountPoint} 0755 root root -") projectList;

      systemd.services = listToAttrs (map ({ name, proj }:
        nameValuePair "autotier-${name}" {
          description = "autotier tiered scratch for lab '${name}' (${proj.mountPoint})";
          wantedBy = [ "multi-user.target" ];
          # network-online for the NFS tier; sssd so the lab group resolves in the
          # perms step. RequiresMountsFor pulls in + orders after every tier mount,
          # so a down cold tier keeps this unit from starting (fail closed) rather
          # than letting autotier demote onto the (impermanent) root.
          after = [ "network-online.target" ]
            ++ optional (proj.ownerGroup != null) "sssd.service";
          wants = [ "network-online.target" ]
            ++ optional (proj.ownerGroup != null) "sssd.service";
          unitConfig.RequiresMountsFor = map (tier: tierPath name tier) proj.tiers;

          serviceConfig = {
            Type = "forking"; # autotierfs daemonizes via fuse_main() (see header)
            ExecStartPre = mkPermsScript name proj;
            ExecStart = ''
              ${cfg.package}/bin/autotierfs -c ${mkConfig name proj} ${proj.mountPoint} -o ${concatStringsSep "," cfg.fuseOptions}
            '';
            ExecStop = "${pkgs.fuse3}/bin/fusermount3 -u ${proj.mountPoint}";
            Restart = "on-failure";
            RestartSec = "30s"; # don't hot-loop while a tier (e.g. NFS) is down
          };
        }
      ) projectList);
    }
  );
}
