# krg.scratch — tiered /scratch via autotier (FUSE), per independent lab.
#
# WHAT: each lab (project) gets ONE merged /scratch/<lab> mount that autotier
# (45Drives, a passthrough FUSE fs) backs with several tiers, fastest-first. New
# writes land on the fastest tier with room; a periodic pass demotes the least
# "popular" files down the tiers and promotes hot ones back up — so the working
# set stays on NVMe and cold data drains to cheaper/larger storage automatically.
#
# WHY autotier and not plain per-pool mounts: the user wanted ONE namespace per
# lab with automatic hot/cold placement (NVMe -> local HDD -> NFS), not a manual
# fast/bulk split. The trade-offs accepted: a FUSE layer (overhead + a daemon
# failure mode) and tier-spanning snapshot semantics. See the design notes below.
#
# WAITER TOPOLOGY (the only consumer today, krg lab only — e4e has no users yet):
#   /scratch/krg  (autotierfs)
#     Tier 1  nvmepool/scratch-krg   -> /srv/scratch-tiers/nvme/krg   (NVMe, hot)
#     Tier 2  hddpool/scratch-krg    -> /srv/scratch-tiers/hdd/krg    (HDD mirror)
#     Tier 3  fabricant NFS          -> /srv/scratch-tiers/nfs/krg    (cold, network)
#
# LAB ISOLATION (krg and e4e are INDEPENDENT labs sharing this box): each lab's
# /scratch and tier roots are chmod 2771, group = that lab's AD group (krg ->
# "Kastner Research Group"), so one lab cannot read another's data even on shared
# hardware. allow_other,default_permissions makes the kernel enforce those modes
# through the FUSE layer. (The tier roots are 2771, not 2770: the `o+x` is REQUIRED
# for autotier's file-create to work at all — see mkPermsScript for the full why.
# It only grants TRAVERSE, not read [no o+r] — non-members can't enumerate the tree,
# and the per-user dirs are 0700, so no data is exposed cross-lab.) The NFS tier is
# exported no_root_squash so autotier (root) preserves each file's owner/group when
# it demotes onto the cold tier.
# With `perUser.enable`, each lab member also gets a private <mountPoint>/<user>
# auto-created on login (a pam_exec session hook, the scratch analogue of
# pam_mkhomedir) — autotier still tiers the whole lab pool underneath.
#
# IMPERMANENCE: the two LOCAL tiers are their own ZFS datasets (off nvmepool/root),
# so they survive the boot rollback untouched. autotier's RocksDB metadata defaults
# to /var/lib/autotier (on the rolled-back root) — it is persisted in
# modules/impermanence.nix, and pointed per-lab at /var/lib/autotier/<lab> so two
# autotier instances never share one RocksDB. If the cold (NFS) tier is down the
# autotier unit FAILS CLOSED (RequiresMountsFor below) rather than demoting files
# onto the ephemeral root — the same hazard the modules/nfs-home.nix login gate
# guards. The local tiers stay durable regardless.
#
# GOTCHA — autotierfs daemonizes. It calls libfuse's fuse_main() and exposes no
# foreground flag, so it double-forks into the background -> the service is
# Type=forking (NOT simple/oneshot, which would mis-track or hang). Stop unmounts
# with fusermount3 (libfuse3: the fuse_operations use copy_file_range/lseek).
{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.krg.scratch;

  # Hardened NFS options for a cold tier — identical posture to modules/nfs-home.nix:
  # _netdev+nofail so a down server never blocks boot, hard so no silent loss once
  # mounted, nconnect for throughput, bounded mount-timeout so a hung server can't
  # stall. The autotier unit's RequiresMountsFor makes "tier down" fail closed.
  nfsTierOptions = [
    "nfsvers=4.2"
    "hard"
    "noatime"
    "nconnect=4"
    "_netdev"
    "nofail"
    "x-systemd.mount-timeout=30s"
  ];

  # Where a tier's backing storage is mounted: <tierMountBase>/<tier.id>/<lab>.
  tierPath = projName: tier: "${cfg.tierMountBase}/${tier.id}/${projName}";

  # Per-lab RocksDB metadata dir (must differ per instance, see header).
  metadataPath = projName: "${cfg.metadataBase}/${projName}";

  # GOTCHA — this autotier/lib45d build MISPARSES a percent quota written with a
  # space before "%": `85 %` is read as 8500% (≈85× the tier, so the demotion
  # watermark never trips), while `85%` parses correctly as 85%. (autotier's own
  # man page / template use the broken `70 %` form.) Normalize by stripping the
  # space before "%"; absolute byte quotas (e.g. "5.3 TiB") have no "%" and pass
  # through untouched. Confirmed on-box 2026-05-22 against autotier 1.2.0.
  normQuota = q: replaceStrings [ " %" ] [ "%" ] q;

  # --- one autotier config file per lab ---------------------------------------
  # autotier.conf: [Global] + one [<label>] section per tier (order = priority,
  # fastest first). Quota is the fullness high-water mark that triggers demotion
  # to the next tier; the last tier is the overflow (Quota = 100 %).
  mkConfig = projName: proj:
    pkgs.writeText "autotier-${projName}.conf" (''
      # Generated by krg.scratch (nix/modules/scratch.nix) — do not edit on-box.
      [Global]
      Log Level = ${toString proj.logLevel}
      Tier Period = ${toString proj.tierPeriod}
      Metadata Path = ${metadataPath projName}
      Copy Buffer Size = ${proj.copyBufferSize}
    ''
    + concatMapStrings (tier: ''

      [${tier.label}]
      Path = ${tierPath projName tier}
      Quota = ${normQuota tier.quota}
    '') proj.tiers);

  # --- ownership / isolation step (ExecStartPre) ------------------------------
  # Runs AFTER the tier mounts are active (RequiresMountsFor) and after sssd, so
  # the AD lab group resolves. Always chmod 2771 the tier roots; chgrp to the lab
  # group only if it resolves — TOLERANT so /scratch still comes up (root-owned,
  # admin-only) before the AD join / group creation lands, then tightens on the
  # next start. The group name has spaces ("Kastner Research Group"), so every
  # path is chgrp'd individually with the group quoted.
  #
  # WHY 2771 (other-execute) and not 2770, given the lab-isolation goal: autotier
  # 1.2.0's FUSE *create* path impersonates the caller with only uid + PRIMARY gid
  # and DROPS supplementary groups, then opens the file on the chosen tier. The
  # only route to a user's files runs through this tier root; with 2770 root:<lab>
  # the impersonated create can't traverse it (the user reaches it only via the
  # supplementary lab group, which autotier discarded) -> EACCES on every file
  # create, for every lab member. (ls/cd/reads work because the kernel's
  # default_permissions check uses the caller's FULL group set; autotier *mkdir*
  # works because it creates as root then chowns — which is also why subdirs come
  # out group `domain users`, not the setgid lab group.) `o+x` lets the
  # impersonated create TRAVERSE the tier root without the group; isolation still
  # holds because there is no `o+r` (non-members can't enumerate the tree) and the
  # per-user dirs are 0700 (no data is readable cross-user/cross-lab). Confirmed
  # on-box 2026-05-22, autotier 1.2.0. (The "correct" alternative — patch autotier
  # to initgroups() in create/open — was declined as too heavy for a dormant tool.)
  mkPermsScript = projName: proj:
    pkgs.writeShellScript "krg-scratch-perms-${projName}" ''
      set -u
      roots="${concatMapStringsSep " " (tier: tierPath projName tier) proj.tiers}"
      for d in $roots; do
        ${pkgs.coreutils}/bin/chmod 2771 "$d" || \
          echo "krg.scratch[${projName}]: chmod 2771 $d failed" >&2
      done
      ${optionalString (proj.ownerGroup != null) ''
        if ${pkgs.getent}/bin/getent group ${escapeShellArg proj.ownerGroup} >/dev/null 2>&1; then
          for d in $roots; do
            ${pkgs.coreutils}/bin/chgrp ${escapeShellArg proj.ownerGroup} "$d" || \
              echo "krg.scratch[${projName}]: chgrp failed on $d" >&2
          done
        else
          echo "krg.scratch[${projName}]: group ${escapeShellArg proj.ownerGroup} not resolvable yet (AD join/group pending?) — tier roots left root-owned (admin-only), will apply on next start" >&2
        fi
      ''}
      exit 0
    '';

  # --- per-user dir creation (pam_exec session hook) --------------------------
  # Runs at session open, as root (before the session drops to the user). Creates
  # <mountPoint>/<PAM_USER> for lab members. GUARDED two ways: (1) only if the
  # scratch mount is active — never create on the bare/ephemeral root when autotier
  # is down (fail-closed cold tier); (2) only for members of ownerGroup, compared by
  # NUMERIC gid since the group name may contain spaces ("Kastner Research Group").
  mkPerUserScript = projName: proj:
    pkgs.writeShellScript "krg-scratch-mkuser-${projName}" ''
      set -u
      [ -n "''${PAM_USER:-}" ] || exit 0
      mp=${escapeShellArg proj.mountPoint}
      ${pkgs.util-linux}/bin/mountpoint -q -- "$mp" || exit 0
      ${optionalString (proj.ownerGroup != null) ''
        gid=$(${pkgs.getent}/bin/getent group ${escapeShellArg proj.ownerGroup} | ${pkgs.coreutils}/bin/cut -d: -f3)
        [ -n "$gid" ] || exit 0
        case " $(${pkgs.coreutils}/bin/id -G "$PAM_USER" 2>/dev/null) " in
          *" $gid "*) : ;;
          *) exit 0 ;;
        esac
      ''}
      d="$mp/$PAM_USER"
      [ -e "$d" ] && exit 0
      ${pkgs.coreutils}/bin/mkdir -p "$d" || exit 0
      ${pkgs.coreutils}/bin/chown "$PAM_USER" "$d" || true
      ${pkgs.coreutils}/bin/chmod ${proj.perUser.mode} "$d" || true
      exit 0
    '';

  tierType = types.submodule ({ ... }: {
    options = {
      id = mkOption {
        type = types.str;
        example = "nvme";
        description = "Short slug for the tier mount path (<tierMountBase>/<id>/<lab>). Must be unique within a lab.";
      };
      label = mkOption {
        type = types.str;
        example = "NVMe";
        description = "autotier section name (shown by `autotier status`, used by `autotier pin`). May contain spaces.";
      };
      fsType = mkOption {
        type = types.enum [ "zfs" "nfs" ];
        description = "How the tier's backing storage is mounted: a local legacy-mountpoint ZFS dataset, or an NFS export.";
      };
      device = mkOption {
        type = types.str;
        example = "nvmepool/scratch-krg";
        description = "fileSystems device: ZFS dataset name (fsType=zfs) or `server:/export` (fsType=nfs).";
      };
      quota = mkOption {
        type = types.str;
        default = "100%";
        example = "85%";
        description = ''
          autotier tier fullness cap that triggers demotion to the next tier; give the
          last (overflow) tier `100%`. Percent (`85%` or `0.85`) or absolute (`5.3 TiB`).
          NOTE: write percentages WITHOUT a space (`85%`, not `85 %`) — this autotier
          build misparses the spaced form as 100× (the module also normalizes it; see
          normQuota). Avoid leading-dot decimals (`.85` misparses to 100%).
        '';
      };
      mountOptions = mkOption {
        type = types.listOf types.str;
        default = [ ];
        description = "Extra mount options appended to the per-fsType defaults.";
      };
    };
  });

  # `attrsOf (submodule …)` binds `name` to the attribute key (the lab name), so
  # mountPoint defaults to /scratch/<lab>. (config below reads the same key via
  # mapAttrsToList, which is why tier paths / metadata / unit names were already right.)
  projectType = types.submodule ({ name, ... }: {
    options = {
      mountPoint = mkOption {
        type = types.str;
        default = "/scratch/${name}";
        description = "The merged FUSE mountpoint users see.";
      };
      ownerGroup = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "Kastner Research Group";
        description = ''
          Lab group that owns this scratch tree (mode 2771, setgid) so other labs
          are denied (o+x grants traverse only, not read; see mkPermsScript). An
          AD/SSSD group (may contain spaces). null = leave root-owned (admin-only).
          When set, the unit orders after sssd so the group resolves.
        '';
      };
      tierPeriod = mkOption {
        type = types.ints.unsigned;
        default = 86400;
        description = "Seconds between autotier demotion/promotion passes. Daily by default — scratch doesn't need aggressive churn, and it keeps NFS-tier traffic down.";
      };
      copyBufferSize = mkOption {
        type = types.str;
        default = "16 MiB";
        description = "autotier inter-tier copy buffer (bulk 1M-recordsize data moves faster with a larger buffer).";
      };
      logLevel = mkOption {
        type = types.enum [ 0 1 2 ];
        default = 1;
        description = "autotier log level (0 none, 1 normal, 2 debug).";
      };
      perUser = mkOption {
        default = { };
        description = ''
          Auto-create a private per-user directory <mountPoint>/<user> on login — a
          pam_exec session hook, the scratch analogue of pam_mkhomedir. Created only
          for members of `ownerGroup`, and only while the scratch mount is actually
          active (never on the bare/ephemeral root). Non-blocking: a failure here
          never denies login (scratch is not critical). autotier still tiers the whole
          lab pool underneath — these dirs just give each user their own namespace.
        '';
        type = types.submodule {
          options = {
            enable = mkEnableOption "per-user directories under this lab's scratch";
            mode = mkOption {
              type = types.str;
              default = "0700";
              description = "Mode for each per-user dir. 0700 = private to the user; 2770 = shared within the lab (setgid).";
            };
            loginServices = mkOption {
              type = types.listOf types.str;
              default = [ "sshd" "login" ];
              description = "PAM services the per-user-dir session hook is added to (mirror krg.nfsHome.loginServices; add xrdp etc. as needed).";
            };
          };
        };
      };
      tiers = mkOption {
        type = types.listOf tierType;
        description = "Tiers fastest-first. At least two required.";
      };
    };
  });
in {
  options.krg.scratch = {
    enable = mkEnableOption "tiered /scratch via autotier (per-lab, FUSE)";

    package = mkOption {
      type = types.package;
      default = pkgs.autotier;
      defaultText = literalExpression "pkgs.autotier";
      description = "The autotier package providing autotierfs.";
    };

    tierMountBase = mkOption {
      type = types.str;
      default = "/srv/scratch-tiers";
      description = "Parent dir under which each tier's backing storage is mounted (admin-facing; users use the merged mountPoint).";
    };

    metadataBase = mkOption {
      type = types.str;
      default = "/var/lib/autotier";
      description = ''
        Parent dir for autotier's per-lab RocksDB metadata (<metadataBase>/<lab>).
        On an impermanent host this must be persisted (see modules/impermanence.nix);
        losing it only costs popularity history (autotier rebuilds), not data.
      '';
    };

    fuseOptions = mkOption {
      type = types.listOf types.str;
      default = [ "allow_other" "default_permissions" ];
      description = ''
        FUSE mount options. default_permissions makes the kernel enforce the
        underlying 2771/file modes (the lab-isolation gate); allow_other lets users
        other than the mounting root (i.e. everyone, gated by those modes) access it.
        allow_other needs programs.fuse.userAllowOther (set below).
      '';
    };

    projects = mkOption {
      type = types.attrsOf projectType;
      default = { };
      description = "Per-lab tiered scratch instances, keyed by lab name.";
      example = literalExpression ''
        {
          krg = {
            ownerGroup = "Kastner Research Group";
            tiers = [
              { id = "nvme"; label = "NVMe"; fsType = "zfs"; device = "nvmepool/scratch-krg"; quota = "85%"; }
              { id = "hdd";  label = "HDD";  fsType = "zfs"; device = "hddpool/scratch-krg";  quota = "90%"; }
              { id = "nfs";  label = "NFS (fabricant)"; fsType = "nfs"; device = "137.110.161.98:/srv/nfs/scratch-krg"; quota = "100%"; }
            ];
          };
        }
      '';
    };
  };

  config = mkIf (cfg.enable && cfg.projects != { }) (
    let
      projectList = mapAttrsToList (name: proj: { inherit name proj; }) cfg.projects;
    in {
      assertions = concatLists (mapAttrsToList (name: proj:
        let
          ids = map (t: t.id) proj.tiers;
          labels = map (t: t.label) proj.tiers;
        in [
          {
            assertion = length proj.tiers >= 2;
            message = "krg.scratch.projects.${name}: autotier needs at least two tiers.";
          }
          {
            # Duplicate ids -> colliding backing mountpoints (<tierMountBase>/<id>/<lab>)
            # -> the generated fileSystems entries clash. `unique` preserves order, so
            # equality holds iff there were no dupes.
            assertion = ids == unique ids;
            message = "krg.scratch.projects.${name}: tier `id`s must be unique (they form the backing mountpoints): ${toString ids}";
          }
          {
            # Duplicate labels -> two autotier [section] headers with the same name.
            assertion = labels == unique labels;
            message = "krg.scratch.projects.${name}: tier `label`s must be unique (autotier section headers): ${toString labels}";
          }
        ]
      ) cfg.projects);

      # allow_other requires user_allow_other in /etc/fuse.conf (even though
      # autotierfs runs as root, libfuse checks it).
      programs.fuse.userAllowOther = true;

      # Admins want `autotier status -c …`, `which-tier`, `pin`, etc. on PATH.
      environment.systemPackages = [ cfg.package ];

      # One backing mount per tier, per lab. Local ZFS tiers mirror disko's legacy
      # mounts (fsType=zfs, "defaults"); we add "nofail" so a scratch hiccup never
      # blocks boot (the autotier unit depends on the mounts via RequiresMountsFor,
      # so it just won't start). The NFS tier uses the hardened nfs-home posture.
      fileSystems = mkMerge (concatMap ({ name, proj }:
        map (tier: {
          ${tierPath name tier} =
            if tier.fsType == "zfs" then {
              device = tier.device;
              fsType = "zfs";
              options = [ "defaults" "nofail" ] ++ tier.mountOptions;
            } else {
              device = tier.device;
              fsType = "nfs";
              options = nfsTierOptions ++ tier.mountOptions;
            };
        }) proj.tiers
      ) projectList);

      # Ensure the merged FUSE mountpoints exist (no .mount unit creates them, unlike
      # the tier backings). 0755 here is just the bare mountpoint; once autotier is
      # mounted the root's perms come from tier 1 (2771, set by the perms step).
      systemd.tmpfiles.rules =
        [ "d /scratch 0755 root root -" ]
        ++ map ({ name, proj }: "d ${proj.mountPoint} 0755 root root -") projectList;

      systemd.services = listToAttrs (map ({ name, proj }:
        nameValuePair "autotier-${name}" {
          description = "autotier tiered scratch for lab '${name}' (${proj.mountPoint})";
          wantedBy = [ "multi-user.target" ];
          # network-online for the NFS tier; sssd so the lab group resolves in the
          # perms step. RequiresMountsFor pulls in + orders after every tier mount,
          # so a down cold tier keeps this unit from starting (fail closed) rather
          # than letting autotier demote onto the (impermanent) root.
          after = [ "network-online.target" ]
            ++ optional (proj.ownerGroup != null) "sssd.service";
          wants = [ "network-online.target" ]
            ++ optional (proj.ownerGroup != null) "sssd.service";
          unitConfig.RequiresMountsFor = map (tier: tierPath name tier) proj.tiers;

          # Do NOT bounce on a routine `nixos-rebuild switch` (incl. the nightly
          # auto-upgrade). The NixOS default restartIfChanged=true reruns ExecStop on
          # ANY closure change, and ExecStop tears down the WHOLE FUSE namespace —
          # killing in-flight tier moves + every open /scratch fd. Worse, if a process
          # holds the mount the unmount fails "busy", leaving a STALE endpoint that makes
          # the next autotierfs SIGABRT in boost::filesystem on its own mountpoint — a
          # crash loop that (2026-05-24) also corrupted the RocksDB metadata and needed a
          # manual wipe + `autotier oneshot` to recover (see docs/troubleshooting.md).
          # With this false, new config needs a DELIBERATE `systemctl restart
          # autotier-${name}` in a quiet window (or a reboot, clean on this impermanence box).
          restartIfChanged = false;

          serviceConfig = {
            Type = "forking"; # autotierfs daemonizes via fuse_main() (see header)
            ExecStartPre = mkPermsScript name proj;
            # Single-line on purpose: systemd unit values are one line, and an
            # indented Nix '' string would leave a trailing newline in ExecStart=.
            ExecStart = "${cfg.package}/bin/autotierfs -c ${mkConfig name proj} ${proj.mountPoint} -o ${concatStringsSep "," cfg.fuseOptions}";
            # Clean unmount first; if the mount is busy, `fusermount3 -u` fails "Device
            # or resource busy" and leaves a STALE endpoint (ENOTCONN) that crash-loops
            # the next start. Fall back to a LAZY detach, which succeeds even when busy and
            # never leaves a zombie (existing fds drain, new access fails). Guard on an
            # actual /proc/mounts entry — which lists a healthy mount AND a stale ENOTCONN
            # endpoint (the latter fails `mountpoint -q`, so don't use that) — so an
            # already-unmounted stop exits cleanly instead of spuriously failing, while a
            # real mount that can't be torn down even lazily is left to surface (non-zero)
            # rather than masked by a blanket `|| true`.
            ExecStop = pkgs.writeShellScript "autotier-${name}-stop" ''
              mp=${escapeShellArg proj.mountPoint}
              ${pkgs.gnugrep}/bin/grep -qF " $mp " /proc/mounts || exit 0
              ${pkgs.fuse3}/bin/fusermount3 -u "$mp" \
                || ${pkgs.fuse3}/bin/fusermount3 -u -z "$mp" \
                || ${pkgs.util-linux}/bin/umount -l "$mp"
            '';
            Restart = "on-failure";
            RestartSec = "30s"; # don't hot-loop while a tier (e.g. NFS) is down
          };
        }
      ) projectList);

      # Per-user dir auto-creation: a session pam_exec hook on the configured login
      # services, for each lab that opts into perUser. `optional` so it can never
      # block a login. Different rule name per lab so multiple labs don't collide.
      security.pam.services = mkMerge (concatMap ({ name, proj }:
        optionals proj.perUser.enable (map (svc: {
          ${svc}.rules.session."krgScratchMkdir_${name}" = {
            control = "optional";
            modulePath = "${pkgs.pam}/lib/security/pam_exec.so";
            args = [ "${mkPerUserScript name proj}" ]; # coerce derivation -> store-path string
            order = 13000; # session open, after pam_mkhomedir
          };
        }) proj.perUser.loginServices)
      ) projectList);
    }
  );
}
